main: fr.snipertvmc.swiftpluginsupdater.Main


name: SwiftPluginsUpdater
version: 0.0.1-alpha
description: Manage updates for your plugins installed on your server and install them automatically.


author: SwiftTeam (Sniper_TVmc)
website: https://github.com/SwiftTeam-Dev/



#commands:
#
#  gamemode:
#    description: "Utilisez cette commande afin de changer votre mode de jeu."
#    aliases: [gm, gamem, gmode]